import { Link, useNavigate } from 'react-router-dom'
import { useState } from 'react'

export default function AuthPage({ mode }) {
  const isLogin = mode === 'login'
  const navigate = useNavigate()
  const [message, setMessage] = useState('')
  function submit(event) { event.preventDefault(); setMessage(isLogin ? 'Welcome back — opening your coffee ritual.' : 'Your account is ready — welcome to Roastery.'); setTimeout(() => navigate('/app'), 550) }
  return <main className="min-h-screen bg-[#20110c] px-5 py-8 font-sans text-[#fff8ed] sm:px-8"><nav className="mx-auto flex max-w-6xl items-center justify-between border-b border-white/20 pb-5"><Link className="font-serif text-xl font-bold tracking-tight" to="/"><span className="mr-2 text-amber-400">✦</span>ROASTERY</Link><Link className="text-xs text-amber-100 hover:text-white" to="/">← Back home</Link></nav><section className="mx-auto mt-14 grid max-w-5xl overflow-hidden rounded-3xl border border-white/15 bg-[#321b12] shadow-2xl md:grid-cols-2"><div className="hidden bg-[radial-gradient(circle_at_50%_30%,#b66a31,#643516_45%,#26140d_80%)] p-12 md:block"><span className="text-xs tracking-[.25em] text-amber-200">YOUR DAILY RITUAL</span><h1 className="mt-8 font-serif text-6xl leading-none">Coffee made<br />for your<br /><em>moment.</em></h1><p className="mt-7 max-w-xs text-sm leading-6 text-amber-100/80">Save your favorites, track your coffee passport, and make every visit count.</p></div><div className="p-7 sm:p-12"><p className="text-xs font-semibold tracking-[.2em] text-amber-300">{isLogin ? 'WELCOME BACK' : 'JOIN THE ROASTERY'}</p><h2 className="mt-3 font-serif text-4xl">{isLogin ? 'Sign in' : 'Create account'}</h2><form className="mt-8 space-y-4" onSubmit={submit}>{!isLogin && <label className="block text-xs font-medium">Full name<input required className="mt-2 w-full rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-sm outline-none focus:border-amber-400" placeholder="Your name" /></label>}<label className="block text-xs font-medium">Email address<input required type="email" className="mt-2 w-full rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-sm outline-none focus:border-amber-400" placeholder="you@example.com" /></label><label className="block text-xs font-medium">Password<input required minLength="6" type="password" className="mt-2 w-full rounded-xl border border-white/15 bg-white/10 px-4 py-3 text-sm outline-none focus:border-amber-400" placeholder="••••••••" /></label><button className="w-full rounded-xl bg-[#e4a25d] px-4 py-3 text-sm font-bold text-[#301608] hover:bg-[#f0b773]">{isLogin ? 'Sign in' : 'Create my account'} →</button></form>{message && <p className="mt-4 rounded-lg bg-amber-300/15 p-3 text-xs text-amber-100">{message}</p>}<p className="mt-7 text-xs text-amber-100/70">{isLogin ? 'New here?' : 'Already have an account?'} <Link className="font-semibold text-amber-300" to={isLogin ? '/register' : '/login'}>{isLogin ? 'Create one' : 'Sign in'}</Link></p></div></section></main>
}
