function LandingPage({ onEnter, onLogin, onRegister }) {
  return <section className="min-h-screen overflow-hidden bg-[radial-gradient(circle_at_77%_41%,#a86228_0,#573016_26%,#1a0f0b_66%)] font-serif text-[#fff8ed]">
    <nav className="relative z-10 flex h-[72px] items-center justify-between border-b border-white/20 px-[7vw] font-sans"><button className="text-lg font-bold" onClick={onEnter}><span className="text-amber-500">&#10022;</span> Roastery</button><div className="hidden gap-7 text-[10px] text-amber-100 md:flex"><button onClick={onEnter}>Home</button><button onClick={onEnter}>Coffee Menu</button><button onClick={onEnter}>Our Story</button></div><div className="flex items-center gap-3"><button className="hidden text-[10px] text-amber-100 hover:text-white sm:block" onClick={onLogin}>Log in</button><button className="rounded-full bg-[#e4a25d] px-4 py-2 text-[10px] font-bold text-[#2c160b]" onClick={onRegister}>Join us</button></div></nav>
    <div className="relative z-10 mx-[10vw] max-w-[32rem] pt-[clamp(5rem,15vh,10rem)] max-md:mx-[7vw] max-md:max-w-[82vw]"><span className="font-sans text-[9px] tracking-[.2em] text-[#d8a46d]">ORIGIN &middot; CRAFT &middot; EXPERIENCE</span><h1 className="my-5 text-[clamp(48px,6.4vw,82px)] leading-[.88] tracking-[-.06em]">Your Coffee.<br />Your Ritual.<br />Your Moment.</h1><p className="max-w-[25rem] font-sans text-xs leading-7 text-[#e6c7a9]">Discover specialty coffee crafted around you. Explore bold flavors, create your perfect cup, and make every visit a ritual worth remembering.</p><button className="mt-5 rounded-full bg-[#e4a25d] px-5 py-3 font-sans text-[10px] font-semibold text-[#2b150b]" onClick={onEnter}>Explore our coffee <span className="pl-2 text-sm">&rarr;</span></button></div>
    <div aria-hidden="true" className="absolute bottom-[4vh] right-[7vw] h-[68vh] w-[min(510px,57vw)] max-md:-right-[10vw] max-md:bottom-0 max-md:h-[49vh] max-md:w-screen"><div className="absolute bottom-0 h-[23%] w-full rounded-[50%] bg-[radial-gradient(ellipse,#bd7a37_0_4%,#75401f_43%,#2c160d_72%)] shadow-[0_-15px_30px_#f5a75544]" /><div className="absolute bottom-[15%] left-[17%] h-[12%] w-2/3 rounded-[50%] bg-[radial-gradient(ellipse,#fff2d2_0_35%,#a96e3b_37%_45%,#32170c_67%)]" /><div className="absolute bottom-[24%] left-[30%] z-20 h-[29%] w-[37%] rounded-t-[9px] rounded-b-[42%] bg-gradient-to-br from-[#fce8bf] to-[#bf7441] shadow-[20px_22px_20px_#12090566]"><div className="absolute left-[7%] top-[7%] h-[18%] w-[86%] rounded-[50%] bg-[radial-gradient(ellipse,#e2a166_0_25%,#3e190e_57%,#160905_70%)]" /></div><div className="absolute bottom-[30%] left-[64%] z-10 h-[16%] w-[17%] rounded-r-[60%] border-[12px] border-l-0 border-[#ca8247]" /><div className="absolute bottom-[46%] left-[40%] h-[40%] w-[22%] rotate-12 rounded-[45%] border-2 border-transparent border-l-[#ffdda877] blur-[5px]" /><div className="absolute bottom-[54%] left-[51%] h-[32%] w-[22%] -rotate-12 rounded-[45%] border-2 border-transparent border-l-[#ffdda877] blur-[5px]" /></div>
  </section>
}

export default LandingPage
