import { useMemo, useState } from 'react'
const drinks=[{name:'Iced Caramel Latte',tag:'Creamy & sweet',emoji:'🧋',color:'#d7a36d'},{name:'Oat Milk Mocha',tag:'Chocolatey & smooth',emoji:'☕',color:'#8d5d43'},{name:'Iced Americano',tag:'Bold & refreshing',emoji:'🥤',color:'#5e3929'}]
function CoffeeQuestPage({onAddToOrder}){
 const [prompt,setPrompt]=useState("I'm tired and want something not too sweet."),[quiz,setQuiz]=useState({temp:'',flavor:'',strength:''}),[quizResult,setQuizResult]=useState('')
 const recommendation=useMemo(()=>{const w=prompt.toLowerCase();if(w.includes('sweet')||w.includes('chocolate'))return drinks[0];if(w.includes('tired')||w.includes('strong'))return drinks[2];return drinks[1]},[prompt])
 const finishQuiz=()=>{if(Object.values(quiz).some(v=>!v))return;setQuizResult(quiz.flavor==='Chocolatey'?'You’re an Oat Milk Mocha person.':quiz.temp==='Cold'?'You’re an Iced Caramel Latte person.':'You’re a Classic Cappuccino person.')}
 return <><section className="page-intro"><span className="eyebrow">COFFEEQUEST</span><h1>Find your perfect pour.</h1><p>A thoughtful recommendation, a seat that fits your day, and your very own coffee profile.</p></section><section className="recommend-grid"><div className="smart-card"><span className="eyebrow">YOUR COFFEE CONCIERGE</span><h2>What are you<br/>feeling today?</h2><div className="prompt"><input value={prompt} onChange={e=>setPrompt(e.target.value)}/><button>↑</button></div><div className="match"><span className="drink-icon" style={{background:recommendation.color}}>{recommendation.emoji}</span><div><span>YOUR 87% MATCH</span><b>{recommendation.name}</b><p>{recommendation.tag}</p></div><button onClick={onAddToOrder}>Add +</button></div></div><div className="study-card"><span className="eyebrow">FIND YOUR SPOT</span><h2>What brings you in?</h2><div className="modes">{[['📚','Study'],['⌨','Work'],['☼','Social'],['◉','Unwind']].map(([icon,text])=><button onClick={()=>alert(`${text} mode: the Window Bar is a great match today.`)} key={text}><b>{icon}</b>{text}</button>)}</div><div className="spot"><span>✦</span><div><b>Window Bar</b><p>Quiet corner · Outlets nearby</p></div><em>Best match</em></div></div></section><section className="quiz"><div><span className="eyebrow">FIND YOUR POUR</span><h2>Your coffee personality</h2><p>Three quick picks, one very good match.</p></div><div className="quiz-options">{[['temp','Hot or cold?',['Hot','Cold']],['flavor','Fruity or chocolatey?',['Fruity','Chocolatey']],['strength','Strong or mild?',['Strong','Mild']]].map(([key,label,answers])=><label key={key}>{label}<div className="pills">{answers.map(answer=><button className={quiz[key]===answer?'selected':''} onClick={()=>setQuiz({...quiz,[key]:answer})} key={answer}>{answer}</button>)}</div></label>)}<button className="dark-btn" onClick={finishQuiz}>Reveal my match</button>{quizResult&&<b className="quiz-result">{quizResult}</b>}</div></section></>
}
export default CoffeeQuestPage
