import { useEffect, useState } from 'react'
import api from '../api'

export default function HomePage({ onNavigate }) {
  const [status, setStatus] = useState({ occupancy: 58, crowd: 'Just right', music: 'Lo-fi & slow', volume: 'Low', wifi: 'Excellent' })
  const [user, setUser] = useState({ streak: 12 })
  useEffect(() => { api.get('/cafe-status').then(({ data }) => setStatus(data)).catch(() => {}); api.get('/users/demo').then(({ data }) => data && setUser(data)).catch(() => {}) }, [])
  return <><section className="grid overflow-hidden rounded-3xl bg-[#2d1911] text-[#fff8ed] md:grid-cols-[1.05fr_.95fr]"><div className="p-8 sm:p-12"><span className="text-xs font-bold tracking-[.2em] text-[#e4a25d]">YOUR DAILY RITUAL, UPGRADED</span><h1 className="mt-5 font-serif text-5xl leading-[.9] sm:text-7xl">Coffee that<br /><em>gets</em> you.</h1><p className="mt-6 max-w-md text-sm leading-6 text-[#ead8c8]">Build your perfect drink, find your focus, and make every visit count.</p><button className="mt-8 rounded-full bg-[#e4a25d] px-5 py-3 text-sm font-bold text-[#2d1911] hover:bg-[#f2bb7a]" onClick={() => onNavigate('Menu')}>Build your coffee →</button></div><div className="relative min-h-72 bg-[radial-gradient(circle_at_53%_35%,#f5c283_0_6%,#b66b32_7%,#673619_30%,#2d1911_68%)]"><div className="absolute bottom-8 left-1/2 h-40 w-32 -translate-x-1/2 rounded-b-[45%] rounded-t-xl bg-gradient-to-br from-[#fbe3bc] to-[#b66c3a] shadow-2xl"><div className="absolute left-[8%] top-[8%] h-8 w-[84%] rounded-full bg-[#3a1a0d]" /><span className="absolute inset-x-0 top-20 text-center text-xs font-bold text-[#4a2614]">ROASTERY<br /><small>EST. 2024</small></span></div><div className="absolute bottom-3 left-1/2 h-12 w-52 -translate-x-1/2 rounded-[50%] bg-[#1d0c06]/60" /></div></section><section className="mt-6 grid gap-4 md:grid-cols-3"><article className="rounded-2xl border border-[#5c321d]/15 bg-white p-6"><span className="text-[10px] font-bold tracking-[.18em] text-[#8a6551]">CAFÉ RIGHT NOW</span><div className="mt-5 flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full bg-emerald-500" /><b>{status.crowd}</b><small className="ml-auto text-xs text-[#8a6551]">{status.occupancy}% occupied</small></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#eadcc9]"><i className="block h-full rounded-full bg-[#b76a32]" style={{ width: `${status.occupancy}%` }} /></div><p className="mt-4 text-sm text-[#72584a]">Good energy, plenty of space.</p></article><article className="rounded-2xl border border-[#5c321d]/15 bg-white p-6"><span className="text-[10px] font-bold tracking-[.18em] text-[#8a6551]">THE VIBE</span><div className="mt-5 flex gap-3"><span className="text-2xl text-[#b76a32]">♫</span><div><b>{status.music}</b><p className="mt-1 text-sm text-[#72584a]">Volume: {status.volume} · Wi‑Fi: {status.wifi}</p></div></div></article><article className="rounded-2xl bg-[#e7d7c1] p-6"><span className="text-[10px] font-bold tracking-[.18em] text-[#72584a]">YOUR STREAK</span><strong className="mt-4 block text-4xl">🔥 {user.streak}<small className="ml-1 text-sm font-normal">days</small></strong><p className="mt-4 text-sm text-[#72584a]">2 more visits to beat your best.</p></article></section></>
}
