import { useEffect, useState } from 'react'
import api from '../../api'
const choices = (values, current, set) => <div className="mt-2 flex flex-wrap gap-2">{values.map(value => <button key={value} onClick={() => set(value)} className={`rounded-full border px-3 py-2 text-xs font-semibold ${current === value ? 'border-[#2d1911] bg-[#2d1911] text-white' : 'border-[#5c321d]/20 bg-white hover:bg-[#eadcc9]'}`}>{value}</button>)}</div>
export default function MenuPage({ onAddToOrder }) {
 const [size,setSize]=useState('Grande'), [milk,setMilk]=useState('Oat milk'), [shot,setShot]=useState(false), [added,setAdded]=useState(false), [coffees,setCoffees]=useState([]), [selected,setSelected]=useState(null), [error,setError]=useState('')
 useEffect(() => { api.get('/coffees').then(({data}) => { setCoffees(data); setSelected(data.find(c => c.name === 'Classic Latte') || data[0]) }).catch(() => setError('Start the server and add starter data to load the menu.')) }, [])
 const total=(selected?.price || 165)+(size==='Venti'?20:size==='Tall'?-10:0)+(shot?30:0)
 async function add(){ try { await api.post('/orders',{coffee:selected?._id,drink:selected?.name || 'Classic Latte',customizations:{size,milk,extraShot:shot},total}); setAdded(true); onAddToOrder() } catch { setError('Your order could not be saved. Check the database connection.') } }
 return <><header className="flex items-end justify-between"><div><span className="text-xs font-bold tracking-[.2em] text-[#ae642e]">MAKE IT YOURS</span><h1 className="mt-2 font-serif text-5xl">Build your coffee</h1></div><span className="text-xs text-[#72584a]">01 — 03</span></header><section className="mt-8 grid overflow-hidden rounded-3xl border border-[#5c321d]/15 bg-white md:grid-cols-[.8fr_1.2fr]"><div className="flex min-h-96 flex-col items-center justify-center bg-[#e7d7c1] p-8"><div className="h-52 w-40 rounded-b-[45%] rounded-t-2xl bg-gradient-to-br from-[#fff3d7] to-[#b76a32] shadow-xl"><div className="mx-auto mt-4 h-10 w-[85%] rounded-full bg-[#482314]" /><p className="mt-16 text-center text-xs font-bold">YOUR<br />COFFEE</p></div><p className="mt-8 text-xs text-[#72584a]">{size} · {milk} · {shot ? 'Double shot' : 'Single shot'}</p></div><div className="p-7 sm:p-10"><h2 className="font-serif text-3xl">{selected?.name || 'Start with a Latte'}</h2><p className="mt-2 text-sm text-[#72584a]">{selected?.description || 'Smooth espresso, steamed milk, and just the way you like it.'}</p>{coffees.length > 0 && <label className="mt-7 block text-xs font-bold tracking-wider">DRINK {choices(coffees.map(c => c.name), selected?.name, name => setSelected(coffees.find(c => c.name === name)))}</label>}<label className="mt-6 block text-xs font-bold tracking-wider">SIZE {choices(['Tall','Grande','Venti'],size,setSize)}</label><label className="mt-6 block text-xs font-bold tracking-wider">MILK {choices(['Whole milk','Oat milk','Almond milk'],milk,setMilk)}</label><label className="mt-6 flex cursor-pointer items-center justify-between rounded-xl bg-[#fffaf2] p-4 text-sm"><span>Extra espresso shot <small className="text-[#72584a]">+ ₱30</small></span><input className="accent-[#2d1911]" type="checkbox" checked={shot} onChange={e=>setShot(e.target.checked)} /></label><div className="mt-7 flex items-center justify-between"><div><b className="text-2xl">₱{total}</b><span className="block text-xs text-[#72584a]">Estimated total</span></div><button className="rounded-full bg-[#2d1911] px-5 py-3 text-sm font-bold text-white" onClick={add}>{added?'Added to order ✓':'Add to order'}</button></div>{error && <p className="mt-4 text-xs text-red-700">{error}</p>}</div></section></>
}
