import { useEffect, useState } from 'react'
import api from '../../api'

export default function RewardsPage() {
  const [user, setUser] = useState({ name: 'JAY D.', passportStamps: 8, achievements: ['Early Bird', 'Latte Master', 'Explorer'] })
  useEffect(() => { api.get('/users/demo').then(({ data }) => data && setUser(data)).catch(() => {}) }, [])
  const stamps = user.passportStamps || 0

  return <main className="min-h-screen bg-[#100c0a] px-5 py-8 font-sans text-[#f2e5d8] sm:px-8 lg:px-10"><div className="mx-auto max-w-[1280px]"><header><span className="text-xs font-bold tracking-[.2em] text-[#d18b4b]">YOUR COFFEEQUEST</span><h1 className="mt-2 font-serif text-5xl">Every cup tells<br />your story.</h1><p className="mt-3 max-w-lg text-sm text-[#c7b3a0]">Keep your streak going, collect stamps, and unlock rewards made for your ritual.</p></header><section className="mt-8 grid gap-5 rounded-3xl border border-[#4d3426] bg-[#1a130f] p-7 md:grid-cols-2 md:p-10"><div><span className="text-xs font-bold tracking-[.2em] text-[#d18b4b]">YOUR COFFEE PASSPORT</span><h2 className="mt-5 font-serif text-4xl">{Math.max(0, 10 - stamps)} more cups<br />for a reward.</h2><button className="mt-7 rounded-full border border-white/25 px-4 py-2 text-xs font-bold hover:bg-white/10">See rewards →</button></div><div className="rounded-2xl bg-[#f4dfba] p-6 text-[#2d1911]"><div className="flex justify-between text-xs font-bold"><span>☕ PASSPORT</span><span>{user.name}</span></div><div className="mt-8 grid grid-cols-5 gap-3">{Array.from({ length: 10 }, (_, i) => <span className={`flex aspect-square items-center justify-center rounded-full border-2 border-[#b76a32] ${i < stamps ? 'bg-[#b76a32] text-white' : ''}`} key={i}>{i < stamps ? '☕' : ''}</span>)}</div><p className="mt-6 text-sm font-bold">{stamps} of 10 coffees <span className="font-normal text-[#72584a]">· {Math.max(0, 10 - stamps)} more until a free drink!</span></p></div></section><section className="mt-6 rounded-2xl border border-[#4d3426] bg-[#1a130f] p-6"><span className="text-[10px] font-bold tracking-[.18em] text-[#c7b3a0]">ACHIEVEMENTS</span><div className="mt-4 flex flex-wrap gap-3">{(user.achievements || []).map((achievement, index) => <b className="rounded-full bg-[#302018] px-4 py-2 text-sm text-[#f2e5d8]" key={achievement}>{['☀', '◉', '☁'][index % 3]} <small>{achievement}</small></b>)}</div></section></div></main>
}
